# Title of your blog; shows in the header
title: Hi
description: A modern personal profile
markdown: kramdown
theme: null
author: "Ben Dietzkis"

ppurl: "http://viewdidappear.github.io/viewDidAppear/pp.html"
url: "http://viewdidappear.github.io"
baseurl: ""

# Social Accounts

github_url: https://github.com/viewDidAppear
instagram_url: this_is_a_ben_desu

# Other

include:
  - _pages
  - tiles
# permalink: pretty
# plugins:
  # - jekyll-feed
  # - jekyll-paginate
  # - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# SCSS

# sass:
  # sass_dir: _sass
  # style: :compressed

# Author settings
author:
  - name: "Ben Dietzkis"
    bio: "I make apps, and I relocated from Melbourne to Tokyo in 2018. I'm a Senior Software Engineer, so I can handle all your tech needs."
    url: 

# Build Settings

exclude: [ Gemfile, Gemfile.lock ]
